### ISSUE TITLE
font not found

### ISSUE THREAD

**Issue by bqdong** [stone-zeng/latex-talk#2]
![image](https://user-images.githubusercontent.com/52027654/132131551-b1cf1d0e-b83d-4b8b-86c7-0d93dbfdc7f4.png)
你好，使用`latexmk latex-talk.tex`编译时出现这个问题，在网上也找不到这个字体的下载地方，这个是付费字体吗？

**Comment by muzimuzhi** [comment]
[Avenir Next] 是 [macOS 自带][macos-big-sur]的商业字体。可以试试换用 [Win Office 带的 Avenir Next LT Pro][lt-pro]

https://github.com/stone-zeng/latex-talk/blob/f7eec7fe39936da94e1b2e7e3def00eb2ab276f0/latex-talk.tex#L113

[Avenir Next]: https://www.fonts.com/font/linotype/avenir-next
[macos-big-sur]: https://support.apple.com/en-us/HT211240
[lt-pro]: https://docs.microsoft.com/en-us/typography/font-list/avenirnextltpro
