### ISSUE TITLE
一则内容矛盾之处

### ISSUE THREAD

**Issue by atxy-blip** [stone-zeng/latex-talk#4]
《文本标记（二）》讲，“`\textbf` 这样的命令是否表达语义？“，然而紧随其后的一页就用 “`\textit` 来表示书名，不免稍微显得破坏了严谨性。

另：用作 `fduthesis` 示例的英文摘要中或许有一处 typo，就不单独提 pr 了（

> arose gradually from theories to explain*ing* observations

**Comment by stone-zeng** [comment]
书或作品名称显然不是强调，用 `\emph` 并不合理；如果定义新命令，又有点麻烦，而且编辑器不会做高亮（VS Code 配合插件会把 `\textit` 显示为 italic）。

「表达语义」本身也是一个值得探讨的问题：

- 只为了几处文本是否有必要额外定义新命令？
- 会不会额外增加别人阅读代码的困难？

我现在更倾向于只对复杂且重复次数较多的东西定义新命令（比如 `zhparen` 那些），如果 LaTeX 的标准命令足以涵盖，可能就直接用了。

**Comment by stone-zeng** [comment]
> 另：用作 `fduthesis` 示例的英文摘要中或许有一处 typo，就不单独提 pr 了（
> 
> > arose gradually from theories to explain*ing* observations


这里 arose ... from theories 是一个整体，后面 to explain 是动词不定式表目的，所以并不是 typo ;)
