### ISSUE TITLE
视频版本与 PDF 版本不一致

### ISSUE THREAD

**Issue by Duququ** [stone-zeng/latex-talk#6]
在 Releases 页面上的 PDF 共有四个版本，按时间顺序依次为：

1. [2019-04-18](https://github.com/stone-zeng/latex-talk/releases/tag/2019-04-18)

2. [2020-03-04](https://github.com/stone-zeng/latex-talk/releases/tag/2020-03-04)

3. [2021-06-02](https://github.com/stone-zeng/latex-talk/releases/tag/2021-06-02)

4. [2022-03-12](https://github.com/stone-zeng/latex-talk/releases/tag/2022-03-12)

其中，2020-03-04 的 PDF 版本对应此 [B 站视频](https://www.bilibili.com/video/BV1RE411W7FS?p=1&vd_source=5bc7271d95c280ba03eec62b7d602971)，我想知道，是否有与[最新版本 2022-03-12](https://github.com/stone-zeng/latex-talk/releases/tag/2022-03-12) PDF 对应的视频讲座呢？

![image](https://user-images.githubusercontent.com/126331827/232386796-03ac663f-73cd-4d54-8dc8-54f558f390f5.png)

**Comment by stone-zeng** [comment]
后面没有录像，所以并没有。
